### PR TITLE
Setup Circle-CI code-climate and testing framework

### PR DESCRIPTION
**Pull request by Jkadhuwa**
#### Description
 - Add Circle-CI integration
 - Add Code Climate integration
 - Set up a testing framework
 - Add a pre-commit hook to run linting script

#### How to Test
- Check for status checks on `pull request`.
- You can run `yarn test` to run all tests.
- Make any changes on ts/js/tsx files and default the set rules and try to commit the changes

#### Any background context you want to add
N/A
#### JIRA

[Finishes AMS-14]

### CODE REVIEW

**Review by habinezadalvan — APPROVED** [review]
LGTM

**Review by minega25 — APPROVED** [review]
Good work. Everything running as expected. However, we still need to integrate database at the CI stage

**Review by harerakalex — CHANGES_REQUESTED** [review]
Well done @Jkadhuwa, if possible can you merge your commits into one to make the work flow perfect.

**Review by minega25 — CHANGES_REQUESTED** [review]
@Jkadhuwa Could you also add a lint check as well

**Comment by Jkadhuwa** [comment]
> Well done @Jkadhuwa, if possible can you merge your commits into one to make the work flow perfect.

Done

**Review by harerakalex — APPROVED** [review]

**Comment by Jkadhuwa** [comment]
> @Jkadhuwa Could you also add a lint check as well

Done

**Review by minega25 — APPROVED** [review]
LGTM

**Pull request merged**
